#!/usr/bin/env node

/**
 * Environment Setup Script
 * This script helps set up the required environment variables for the project
 */

const fs = require('fs');
const path = require('path');

const envPath = path.join(process.cwd(), '.env.local');
const envExamplePath = path.join(process.cwd(), '.env.example');

// Default environment variables
const defaultEnvVars = {
  'NEXT_PUBLIC_SUPABASE_URL': 'https://pozoauxismiqgytbsjic.supabase.co',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY': 'your_supabase_anon_key_here',
  'NEXT_PUBLIC_SUPABASE_REDIRECT_URL': 'https://ugenpro.site/login',
  'NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL': 'http://localhost:3000/login',
  'ADMIN_EMAIL': 'admin@ugenpro.site',
  'ADMIN_PASSWORD': 'your_admin_password_here'
};

function createEnvFile() {
  console.log('🔧 Setting up environment variables...\n');

  // Check if .env.local already exists
  if (fs.existsSync(envPath)) {
    console.log('⚠️  .env.local already exists. Backing up to .env.local.backup');
    fs.copyFileSync(envPath, envPath + '.backup');
  }

  // Create .env.local file
  let envContent = '# UGen Pro Environment Variables\n';
  envContent += '# Generated by setup script\n\n';

  Object.entries(defaultEnvVars).forEach(([key, value]) => {
    envContent += `${key}=${value}\n`;
  });

  fs.writeFileSync(envPath, envContent);

  console.log('✅ Created .env.local file with default values');
  console.log('\n📝 Please update the following values in .env.local:');
  console.log('   - NEXT_PUBLIC_SUPABASE_ANON_KEY: Your actual Supabase anon key');
  console.log('   - ADMIN_PASSWORD: Your admin password');
  console.log('\n🔗 Get your Supabase credentials from:');
  console.log('   https://app.supabase.com/project/pozoauxismiqgytbsjic/settings/api');
}

function createEnvExample() {
  if (!fs.existsSync(envExamplePath)) {
    let exampleContent = '# UGen Pro Environment Variables Example\n';
    exampleContent += '# Copy this file to .env.local and update the values\n\n';

    Object.entries(defaultEnvVars).forEach(([key, value]) => {
      exampleContent += `${key}=${value}\n`;
    });

    fs.writeFileSync(envExamplePath, exampleContent);
    console.log('✅ Created .env.example file');
  }
}

function main() {
  console.log('🚀 UGen Pro Environment Setup\n');
  
  createEnvExample();
  createEnvFile();
  
  console.log('\n🎯 Next Steps:');
  console.log('1. Update .env.local with your actual Supabase credentials');
  console.log('2. Run: npm run dev');
  console.log('3. Test authentication at: http://localhost:3000/login');
  
  console.log('\n📋 Supabase Dashboard Configuration:');
  console.log('Site URL: https://ugenpro.site');
  console.log('Redirect URLs:');
  console.log('  - https://ugenpro.site/auth/callback');
  console.log('  - https://ugenpro.site/login');
  console.log('  - https://ugenpro.site/signup');
  console.log('  - https://ugenpro.site/reset-password');
  console.log('  - https://ugenpro.site/change-password');
  console.log('  - https://ugenpro.site/profile');
}

if (require.main === module) {
  main();
}

module.exports = { createEnvFile, createEnvExample };
